### ISSUE TITLE
Hollow Documentation 

### ISSUE THREAD

**Issue by rpalcolea** [Netflix/hollow#101]
Are there plans to open source the docs in http://hollow.how? It would be nice to contribute with things like the incremental producer, google cloud storage and other examples

**Comment by rpalcolea** [comment]
Any thoughts on this @toolbear ? oh just discovered the `gh-pages` branch. Do you use a generator for it? or is it ok to open PRs against it?

**Comment by rpalcolea** [comment]
oh just discovered the `gh-pages` branch

**Comment by rpalcolea** [comment]
thoughts @dkoszewnik ? :)

**Comment by dkoszewnik** [comment]
+1.  I'm sure the team is open to accepting contributions here.

We use [MkDocs](http://www.mkdocs.org/) to build the documentation site.  There is an internal repository here at Netflix which contains the source markup, and we manually regenerate the html and commit to the `gh-pages` branch.  

@kineshsatiya made the most recent changes to the documentation site, including the awesome theme update.  I think we should rely on his judgement about how best to handle accepting contributions.

One way to go might be to migrate our internal repo to a new branch in this project, to which contributions could be made in the form of a PR.

**Comment by rpalcolea** [comment]
👍 that would be great :)

**Comment by ghost** [comment]
@rpalcolea we do have plans to do this.

The `gh-pages` branch is the output of a separate generator (mkdocs) whose source is a private Netflix repo currently. PRs against that will likely get overwritten, so I'm reluctant to suggest that even though it would be the most convenient way for you to convey the edits you want made.

If you have a block of content documenting the blob cleaner that you want to paste as Markdown in this issue, I'll make sure we fold it into our private repo and republish. If the docs for the cleaner would end up sprinkled in a few places throughout, let's discuss an alternate plan.

In terms of general purpose documentation contributions, mind waiting a bit longer while we make the documentation source public?

**Comment by rpalcolea** [comment]
Hi @toolbear, that sounds good to me.

What do you think about the next for the "Tooling" section?

# Blob Storage Manipulation Tools
## Cleaning

Using the `BlobStorageCleaner` capability, it's possible to free up the blob storage and prevent running out of space because of old snapshots/deltas.

Hollow ships with `HollowFilesystemBlobStorageCleaner` which allows to only keep a given number of snapshots. It can be used in the following way:

```java
HollowProducer.Publisher publisher = new HollowFilesystemPublisher(publishDir);
HollowProducer.BlobStorageCleaner blobStorageCleaner = new HollowFilesystemBlobStorageCleaner(publishDir, 10);
HollowProducer producer = HollowProducer.withPublisher(publisher)
                                                .withBlobStorageCleaner(blobStorageCleaner)
                                                .build();
```

The integer `10` parameter will set the value for `numOfSnapshotsToKeep`.

It is also possible to add your own blob storage cleaner by extending `HollowProducer.BlobStorageCleaner` class and provide your own mechanism to clean snapshots/deltas/reversedeltas. This could be used with S3 or Google Cloud Storage buckets for example

**Comment by rpalcolea** [comment]
What about the metrics collector? I think that could be part of "The Producer/Consumer APIs". Let me know your thoughts on that... I guess it would be enough to mention that you can get collect metrics and show an example using prometheus.

**Comment by ghost** [comment]
Docs are now part of this repository. Regenerating and deploying the site requires manual work, so ping in Gitter if you want something published. Closing this.

@rpalcolea feel free to open a PR with the edits you suggested in https://github.com/Netflix/hollow/issues/101#issuecomment-337699239
