### ISSUE TITLE
Hollow Object to JSON directly

### ISSUE THREAD

**Issue by maiakhoa** [Netflix/hollow#123]
Can anyone help me with this issue? I would like to serialize the object I get from Hollow to JSON directly instead of converting it to POJO class and use Jackson to serialize it.
Or do we have any way to get the POJO class after findMatch() method?

Thank you so much

**Comment by dkoszewnik** [comment]
Hi @maiakhoa, check out the `HollowRecordJsonStringifier`:

```
HollowRecordJsonStringifier stringifier = new HollowRecordJsonStringifier(true, true);

/// either
stringifier.stringify(hollowConsumer.getStateEngine(), "TypeName", ordinal);
/// or
stringifier.stringify(someHollowRecord);
```

**Comment by maiakhoa** [comment]
Thank you so much @dkoszewnik. I can solve my issue now.
Currently, I'm converting the HollowRecord to POJO class manually (one by one field). Could you tell me which is the best way to handle that?
