### ISSUE TITLE
Add ability to use a hash index on nullable fields

### ISSUE THREAD

**Issue by dkoszewnik** [Netflix/hollow#128]
When creating a hash index on a nullable field, `ArrayOutOfBoundsException` is thrown from `FixedLengthElementArray:94`.

**Comment by tdudzik** [comment]
Can we expect that this feature will be implemented in the near future?

Is it at least possible to implement without any hacks? Hollow is quite new for me, especially source code, but I was investigating this issue and it seems to be hard to evaluate if the value is `null` having only `ordinal`.

**Comment by tdudzik** [comment]
What is the status of this issue? Can we expect that it will be done in some near future?

**Comment by ghost** [comment]
@tdudzik @dkoszewnik I'll take a look this week.
