### ISSUE TITLE
Data Model with inheritence

### ISSUE THREAD

**Issue by ctatineni** [Netflix/hollow#14]
Hello,

 1)  if i extend Movie class with some abstract class which has primary key column name id, how do i retrieve the data at the consumer using primary key? , even if i try to retrieve all movies , i do not see _getID  in MovieHollow object.

2) is there way to convert Hollow objects back to data model objects on consumer?

**Comment by dkoszewnik** [comment]
Hi, good suggestion in (1).  We don't currently support POJOs with a class hierarchy, but I believe we can.  I'll experiment with this.

As for (2), there is not an automatic way to go back to POJOs on the consumer.

**Comment by ctatineni** [comment]
Thanks, one more thing. seems like transient variables are not ignored.

**Comment by dkoszewnik** [comment]
Hi, (1) is now addressed in release [v2.2.0](https://github.com/Netflix/hollow/releases/tag/v2.2.0).  Thanks again for this suggestion.
