### ISSUE TITLE
APIGenerator NPE

### ISSUE THREAD

**Issue by leotu** [Netflix/hollow#19]
how.hollow.consumer.api.APIGenerator.java occur NPE when listFiles return null value.
(apiCodeFolder doen't exist)

```java
for(File f : apiCodeFolder.listFiles())
     f.delete();
```

maybe add some code like this
```java
if (!apiCodeFolder.exists()) {
     apiCodeFolder.mkdirs();
}
```

Sorry, this issue is not on this project, I posted on wrong project :-),  pls invalid it!

**Comment by dkoszewnik** [comment]
Duplicate of https://github.com/Netflix/hollow-reference-implementation/issues/4
