### ISSUE TITLE
Start a micro-benchmark project

### ISSUE THREAD

**Issue by ghost** [Netflix/hollow#231]
[Gitter discussion](https://gitter.im/Netflix/hollow?at=5b0f6720361a950a662bd94b)

Initial thoughts:

* [ ] separate project/repo
* [ ] run in response to releases
  * [ ] candidate builds from push to `master`
  * [ ] RCs made using GitHub release UI
  * [ ] releases made with UI
* [ ] also compare with a baseline version (perhaps 3.0.0) to also catch gradual drift that might otherwise be missed
* [ ] collect and report metrics somewhere to generate graphs

**Comment by DanielThomas** [comment]
I added some benchmarks here - https://github.com/Netflix/hollow/pull/300. A separate project would make sense, as it'd let you run them out of band to the normal release project, using Gradle composites for local development and evaluating the impact of change as you make it.

**Comment by PaulSandoz** [comment]
Fixed in #361
