### ISSUE TITLE
AbstractHollowOrdinalIterable 's iterator() method is not idempotent

### ISSUE THREAD

**Issue by blekit** [Netflix/hollow#243]
Hi,

during development of our sollution backed by Hollow, we've noticed that `iterator()` method in `AbstractHollowOrdinalIterable` class is not idempotent and invoking it might corrupt wrapped `HollowOrdinalIterator`.

Each time `iterator` in `AbstractHollowOrdinalIterable` is called it creates a new instance of `Iterator` interface and during its initialization invokes `next()` method of underlying `HollowOrdinalIterator`. As a result, we've observed that some of the ordinals might be omitted during later processing if `iterator()` was called more than once (directly or indirectly - e.g. by calling `spliterator` method).

Cheers!

**Comment by rpalcolea** [comment]
I think this issue could be closed now

**Comment by rpalcolea** [comment]
@blekit ^^

**Comment by blekit** [comment]
Yeah, it definitely can.
