### ISSUE TITLE
Hollow History UI has hardcoded time zone

### ISSUE THREAD

**Issue by tnn2** [Netflix/hollow#258]
https://github.com/Netflix/hollow/blob/f0126b04575a897b3e7ceefa07baa0f354b79683/hollow-diff-ui/src/main/java/com/netflix/hollow/history/ui/VersionTimestampConverter.java#L27

For the sake of international users please consider changing this to use the JVM's default time zone as provided by the host.

**Comment by rpalcolea** [comment]
I don't think using JVM's default time zone would be ideal specially if you deploy the history UI using UTC (as a lot of people do).

With that said, I just opened a pull request that adds a new `TimeZone` parameter to the `HollowHistoryUI ` and `HollowHistoryUIServer` so users can specify it

https://github.com/Netflix/hollow/pull/261

**Comment by tnn2** [comment]
Thanks, I'm happy with this solution.
