### ISSUE TITLE
Allow circular type references

### ISSUE THREAD

**Issue by DanielThomas** [Netflix/hollow#306]
Circular references are currently disallowed, but we have an type that is self-referential that would provide a significant producer performance and memory overhead reduction if we could map the type directly.

We represent dependency paths with the following class (Kotlin for the uninitiated):
```
class Path<T : Versioned>(val last: T, val root: Path<T>? = null) : Comparable<Path<T>>, Iterable<Path<T>> {
    val list: List<T>
        get() = (root?.list ?: emptyList()) + last
    val size: Int
        get() = (root?.size ?: 0) + 1

    fun fork(id: T) = Path(id, this)
    fun replaceLast(id: T) = Path(id, root)

    ...
}
```

For our legacy on-heap implementation we gain a significant reduction in the number of objects we need to store as our JSON deserializer for these classes build paths up from their roots, retaining references as they go:

```
0 = {Path@3273} "com.amazonaws:aws-java-sdk-kms:1.11.390 -> com.amazonaws:aws-java-sdk-core:1.11.390"
 last = {ModuleDependency@4558} "ModuleDependency(id=com.amazonaws:aws-java-sdk-core:1.11.390, classifier=null)"
 root = {Path@4559} "com.amazonaws:aws-java-sdk-kms:1.11.390"
  last = {ModuleDependency@4638} "ModuleDependency(id=com.amazonaws:aws-java-sdk-kms:1.11.390, classifier=null)"
  root = null
1 = {Path@3274} "com.amazonaws:aws-java-sdk-kms:1.11.390 -> com.amazonaws:aws-java-sdk-core:1.11.390 -> commons-logging:commons-logging:1.2"
 last = {ModuleDependency@4840} "ModuleDependency(id=commons-logging:commons-logging:1.2, classifier=null)"
 root = {Path@3273} "com.amazonaws:aws-java-sdk-kms:1.11.390 -> com.amazonaws:aws-java-sdk-core:1.11.390"
  last = {ModuleDependency@4558} "ModuleDependency(id=com.amazonaws:aws-java-sdk-core:1.11.390, classifier=null)"
  root = {Path@4559} "com.amazonaws:aws-java-sdk-kms:1.11.390"
   last = {ModuleDependency@4638} "ModuleDependency(id=com.amazonaws:aws-java-sdk-kms:1.11.390, classifier=null)"
   root = null
...
```

Right now, we need to serialize those as regular lists, so for 67,741,900 `ListOfModuleDependency` we have a total of 912.8 MB. Those lists contain _338,849,893_ elements, whereas the `Path` approach has one instance per distinct path, so would be 20% the number of references.

They also have the benefit of not needing https://github.com/Netflix/hollow/issues/302 to optimize de-duplication, as they're the perfect case for POJO memoization. Here's our current hierarchy - there is one `ListOfModuleDependencyList` per `Module`:

<img width="1606" alt="screen shot 2018-10-17 at 2 50 55 pm" src="https://user-images.githubusercontent.com/1479220/47118456-249d3580-d21c-11e8-9e89-80ad6bec2388.png">

We use the `ModuleDependencyList` holder type to expose the head and tail dependency to allow consumer indexing. Right now an hash index on `dependency` takes a minute to create, so I'll likely add another type that groups `ModuleDependencyList` by `dependency` to reduce the cardinality.

**Comment by ghost** [comment]
While I see value for this feature and see the need for your use case (and a few others within Netflix as well), I'm going to close because it isn't on our roadmap and I don't want to leave it in backlog limbo.

The team thinks it's a good idea. However, the effort in core Hollow to implement it plus the changes to tools which assume cycles cannot occur is substantial. Other features we have planned continue to win out over this one. One of those features -- moving towards Java interfaces for both Producer POJOs and the Consumer API -- might also provide a way for users to approximate cycles/foreign-references themselves.

Feel free to like this issue and or add comments as we'll reevaluate whether to work on this feature in future quarters.

**Comment by DanielThomas** [comment]
@toolbear I wouldn't advocate for any change to allow for cycles, just references between the types. Is a type definition containing a reference to it's own type the concern, or actual cycles?

**Comment by ghost** [comment]
@DanielThomas, unfortunately self referential types or a cycle across types are equally problematic. I.e. `A -> A` or `A -> B -> A` lead to the same infinite loop/recursion in core Hollow as well as tooling that currently assume you cannot get back to a type by following references from that type.
