### ISSUE TITLE
HollowAnnouncementWatcher should implement an interface

### ISSUE THREAD

**Issue by brettwooldridge** [Netflix/hollow#33]
Currently, the ``HollowClient`` constructor accepts an instance of ``HollowAnnouncementWatcher``.  Because ``HollowAnnouncementWatcher`` is an abstract class that unconditionally constructs an internal ``Executors.newFixedThreadPool`` instance, this does not scale to deployments where there are hundreds or thousands of ``HollowClient`` instances in a single VM.

While it would be ideal if ``HollowAnnouncementWatcher`` were merely an interface, like ``HollowBlobRetriever`` and other types passed to the ``HollowClient`` constructor, that would be a breaking change for existing code.

Maybe introduce a new interface type, have ``HollowAnnouncementWatcher`` implement that type, and have the ``HollowClient`` accept that type.  That would preserve compatibility for existing clients, while allowing alternative implementations.

EDIT: For context, the use case is multi-tenancy, where each tenant (possibly thousands) has their own data model instances with independent namespaces, snapshots, and delta chains.

**Comment by csueiras** [comment]
+1
