### ISSUE TITLE
Generate primary key beans for UniqueKeyIndex builder

### ISSUE THREAD

**Issue by DanielThomas** [Netflix/hollow#388]
Where a type has a `@HollowPrimaryKey` declared generate the `@FieldPath` bean automatically to avoid duplicating the declaration of primary key fields.

Likely makes sense to make this a nested class so `UniqueKeyIndex` can provide a `fromPrimaryKey` method that expects this class to exist by convention and can build the index in a single shot.

**Comment by PaulSandoz** [comment]
I don't want to bake a convention into the library. Here is another possible way:
- generate a static nested bean class within generated API type that has a primary key; and 
- define a static method on that API type that builds and returns the unique index.

**Comment by PaulSandoz** [comment]
Fixed in #398
