### ISSUE TITLE
SchemaNotFoundException when using UniqueKeyIndex 

### ISSUE THREAD

**Issue by marcel-ghayyeda** [Netflix/hollow#427]
### When hollow-generated class' name is postfixed, UniqueKeyIndex cannot find HollowSchema.  

Example of HollowAPIGenerator creation:
`  new HollowAPIGenerator.Builder().withClassPostfix("Hollow")...
`

In this case, the name of hollow-generated class from https://github.com/Netflix/hollow/releases/tag/v4.1.0 example would be _MovieHollow_.
Schema name would still be just _Movie_. 

In this case, UniqueKeyIndex **cannot** be built using this piece of code:
`UniqueKeyIndex.from(consumer, Movie.class).bindToPrimaryKey()...`

This is caused by _bindToPrimaryKey_ method implementation, which seeks for HollowSchema using _uniqueType_'s simple name, which in this case is _MovieHollow_, whereas schema name is _Movie_.

Mentioned method seeks for HollowSchema using the following piece of code:

` String primaryTypeName = uniqueType.getSimpleName();
HollowSchema schema = consumer.getStateEngine().getNonNullSchema(primaryTypeName);
`

**Comment by PaulSandoz** [comment]
Same issue with `HashIndex` and `HashIndexSelect`, and edge case issues if generating from a schema not derived from producer class files (POJOs) for type names that contain incompatible characters (see `HollowCodeGenerationUtils.hollowImplClassname`).

We need to enhance the API generator to annotate a class with the schema name if it differs from the classes's simple name.  The annotation `HollowTypeName` could be reused.
