### ISSUE TITLE
NPE for fields with types: Collection, Iterable etc

### ISSUE THREAD

**Issue by jan-zywczak** [Netflix/hollow#44]
I'm not sure what should be correct behaviour in this case, but NPE is there worst one - you have to debug application to find our what was the reason. Maybe just a IllegalArgumentException with information that only List, Set and Map types are supported. Or maybe you can storage all Collections or Iterables the same way as List is serialized.

**Comment by dkoszewnik** [comment]
Thanks very much.  Fixed by #48, released in [v2.4.3](https://github.com/Netflix/hollow/releases/tag/v2.4.3)
