### ISSUE TITLE
Feedback on experimental Producer API

### ISSUE THREAD

**Issue by brettwooldridge** [Netflix/hollow#49]
@toolbear I thought I'd offer some thoughts on the new Producer API under development.

It looks pretty good in general except for one bit which is a show-stopper for my company's use.  We persist [snapshots and deltas] in a database, not in files.  So, the fact that ``Blob`` is a concrete class prevents the use of the new API.

If ``Blob`` was and interface, and ``Blob.withNamespace()`` replaced with a call to a user configurable factory, that would be perfect.  Of course, it is perfectly reasonable to default to an implemention that is file-backed.

Maybe the existing ``HollowProducer`` constructor could utilize the default implementation, and a new constructor with one additional parameter (``HollowProducer.BlobFactory``) added?  Something along the lines of:
```java
public HollowProducer(
            Publisher publisher,
            Validator validator,
            Announcer announcer) {
    this(publisher, validator, announcer, new FileBackedBlobFactory());
}

public HollowProducer(
            Publisher publisher,
            Validator validator,
            Announcer announcer,
            BlobFactory blobFactory) {
    ...
}
```

I *think*, having not actually been able to utilitize the new API, that this may be the only change required to support our use-case.

**Comment by dkoszewnik** [comment]
@brettwooldridge Thanks for the feedback.  An early iteration of this API actually did have the filesystem usage abstracted away, but I suggested [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) because I couldn't foresee a case where it wouldn't be reasonable to stage blobs on a filesystem -- regardless of their ultimate destination.  

Even though your blobs are ultimately persisted in a database, is your producer running in an environment that doesn't have access to a filesystem to temporarily stage the blobs?

**Comment by brettwooldridge** [comment]
@dkoszewnik There are a couple of issues I'll see if I can articulate.  One is I/O.  Given that our server is often co-resident with the database, a file-based solution effectively doubles I/O; write the snapshot/delta to a file, read the snapshot/delta from the file, insert the blob into the database (writing to the transaction log), commit the transaction (read the transaction log and write to the table).

In our case, we can have several thousand namespaces, one per-tenant in a multi-tenancy environment, and therefore several thousand delta-streams, each with snapshots sized in megabytes.  Update frequency is hard to gauge, and will vary quite a bit by tenant.

Another concern is storage.  Given that the implementation stores in /tmp ("java.io.tmp") there is some concern about a [rouge wave](https://en.wikipedia.org/wiki/Rogue_wave) in which due to pure bad timing /tmp could be exhausted.  Did I mention our server is a white-box solution and we don't have complete control over the customer's deployment?  😬 

In any case, it seems that a streams-based design (``Input/OutputStream``) for blob storage and retrieval provides flexibility -- stream into a file, stream to a DB, stream over a WebSocket, whatever.  

How annoying would an HTTP client library be if the POST functionality only took a ``File`` as a parameter?  Sure it's *workable*, but who would want to write to a temp file just to execute a POST?

Lastly, and selfishly, we have already implemented our DB-backed solution, using the HollowBlobWriter etc.  We were interested the new new producer API because it seemed simpler, and if it remained stream-based would certainly be easier to swap into our existing implementation.

**Comment by ghost** [comment]
@brettwooldridge, I guess we tend to look at problems through a cloud computing lens, it's been a long time since I had a co-resident DB 😅 

We liked the reduced complexity when we removed that generalization, but yours is a reasonable use-case. I'll look again at providing a streams-oriented blob API.

**Comment by dkoszewnik** [comment]
@brettwooldridge Thanks again for the feedback.  This has been incorporated into the design of the `HollowProducer`.  When [creating a `HollowProducer`](http://hollow.how/producer-consumer/#the-hollowproducer) you can specify a `BlobStager`, which will allow you to stage blobs in a location other than the filesystem.  If you preferred to stage them in memory, you can use the following:

```java
HollowProducer producer = HollowProducer.withPublisher(publisher)
                                        .withBlobStager(new HollowInMemoryBlobStager())
                                           ...
                                        .build();
```

If you prefer to stage blobs in a place other than either the filesystem or memory (e.g. a database), then that can be accomplished with a custom implementation of the `BlobStager` interface.
