### ISSUE TITLE
Compiler errors in IDE for Unsafe

### ISSUE THREAD

**Issue by ghost** [Netflix/hollow#5]
In the `hollow` subproject I get a handful of compiler errors regarding the use of `sun.misc.Unsafe`. For example:

```
Access restriction: The type 'Unsafe' is not API
Access restriction: The method 'Unsafe.getLong(Object, long)
…
```

For me this happens after a pristine import into Eclipse. It may fail for other IDEs.

**Comment by kineshsatiya** [comment]
Upon running gradle build in hollow subproject using intelliJ IDE, I get a couple of warnings.

```
Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
```

Another issue, that I see, errors in my IDE in project hollow-diff-ui
```

hollow/hollow-diff-ui/src/tools/java/com/netflix/hollow/diff/ui/DiffUITest.java:3: error: package org.junit does not exist
import org.junit.Test;
                ^
hollow/hollow-diff-ui/src/tools/java/com/netflix/hollow/diff/ui/DiffUITest.java:6: error: cannot find symbol import com.netflix.hollow.diffview.FakeHollowDiffGenerator;
```

**Comment by ghost** [comment]
I was able to get Eclipse working by changing "Forbidden Reference" to `Warning` under *Java Compiler* → *Errors/Warnings* → *Deprecated and restricted API*

![image](https://cloud.githubusercontent.com/assets/358202/20855828/a491860e-b8b7-11e6-9732-289340535c47.png)
