### ISSUE TITLE
Data Corruption: overflow when retrieving array start and end index

### ISSUE THREAD

**Issue by mikemuske** [Netflix/hollow#513]
When using arrays in Hollow data, for example records that have a few arrays of strings as properties, a bug appears once enough unique arrays are created such that the sum of all their elements exceeds 2^28. We have encountered this bug with several datasets internally.

The root of the problem is that HollowListTypeReadStateShard tries to read both the start index and the end index of an array in a single double-wide read. When the total count of elements exceeds 2^28, the double wide read is 29*2=59 bits. When the bit offset is 7 bits unaligned, the 7 bit shift causes data to be lost, corrupting the end index.

Please see this PR for some test cases and a fix: https://github.com/Netflix/hollow/pull/512

**Comment by dkoszewnik** [comment]
Fixed in `v5.2.2` (please use `v5.2.4` to pick up an additional bugfix).  Thanks very much again for the detective work and PR to address this.
