### ISSUE TITLE
Data Corruption: overflow when calculating snapshot

### ISSUE THREAD

**Issue by mikemuske** [Netflix/hollow#515]
After fixing issue #513 we ran into another overflow for a dataset with billions of array elements, this time in `HollowListTypeWriteState`. The `elementCounter[]` inside `calculateSnapshot()` is holding an `int` for each shard, and when counting array elements this value overflows when there are more than `Integer.MAX_VALUE` elements in a single shard.

It looks like this issue was already addressed in `calculateDelta()` since its `elementCounter[]` is holding `long` values.

**Comment by mikemuske** [comment]
@dkoszewnik

**Comment by dkoszewnik** [comment]
Released your PR  (#516) as `v5.2.5`.  Thank you!
