### ISSUE TITLE
Maintain CHANGELOG.md

### ISSUE THREAD

**Issue by brettwooldridge** [Netflix/hollow#55]
Can we start updating the [CHANGELOG.md](https://github.com/Netflix/hollow/blob/master/CHANGELOG.md) at each release?

It would be really nice to know what was changed so users can make an informed decision about upgrading without reading the commit history.  I've got a [change log](https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES) on a one-man-project running for several years, updating it at release is not a barrel of fun but typically only takes 5-10 minutes.

**Comment by aburghelea** [comment]
I know this is up to the maintainers to answer, but they have this for now https://github.com/Netflix/hollow/releases . I agree that would be useful.

**Comment by brettwooldridge** [comment]
@aburghelea Ah yes, that is somewhat helpful.
