### ISSUE TITLE
Detecting changes

### ISSUE THREAD

**Issue by brettwooldridge** [Netflix/hollow#58]
I know that I can figure out ordinals that were added or removed on the client by intersecting the BitSets, etc.  But how do I find out what Hollow objects *changed* but retained the same ordinal?  I need to act on all changes, and iterating all of the objects and comparing it to the operational state that is based off of them does not scale.

**Comment by brettwooldridge** [comment]
Also, can I expect that the ordinal for object<sup>X</sup> will remain constant between delta<sup>1</sup> and delta<sup>2</sup>?

**Comment by dkoszewnik** [comment]
Individual records are never modified in Hollow -- modifications are always accomplished with a removal of the old record and addition of the new record.

It is guaranteed that if an exactly equivalent record exists in two adjacent states, then that record will retain the same ordinal. If, on the other hand, a record does not have an exact equivalent in an adjacent state, then its ordinal will not be populated in the state in which it does not exist.
