### ISSUE TITLE
Delta / Snapshot cleanup [question]

### ISSUE THREAD

**Issue by rpalcolea** [Netflix/hollow#93]
I brought this last month on Gitter:

> Hi, curious about how people is managing historical of snapshots.
> We’ve been running a hollow producer for about 2 months and hit 1.27 TiB of snapshots.

On that time 2 of the chat members replied with some ideas to clean this up: 3 lifecycle after few days of use or  lambda on a timer to manage our s3 with a ttl on last updated and keeping the newest few snapshots.

While I like the idea of having something external like S3 lifecycle or a Google Cloud Function, there's always the risk of losing files since this might not be aware of the usage by Hollow.

I was wondering is there is a desire to have something built in the hollow producer to remove old deltas and snapshots. Allow the producer to remove files from the blob storage every time there's a new snapshot or delta and let users to set the numbers of files to keep or just let them plug their own implementation so they can determine if they want to keep 'x' number of files or based on dates.

Something in the lines of `BlobStorageCleaner`.

```java
MyBlobStorageCleaner blobStorageCleaner = new MyBlobStorageCleaner();
HollowProducer producer = HollowProducer.withBlobStorageCleaner(blobStorageCleaner);
```

The `BlobStorageCleaner` could be 

```java
public abstract class BlobStorageCleaner {
   public void clean(Blob.Type blobType) {
        switch(blobType) {
        case SNAPSHOT:
            cleanSnapshots();
            break;
        case DELTA:
            cleanDeltas();
            break;
        case REVERSE_DELTA:
            cleanReverseDeltas();
            break;
        }
    }
   abstract void cleanSnapshots();
   abstract void cleanDeltas();
   abstract void cleanReverseDeltas();
}
```

And this could be triggered after `fireArtifactPublish` is triggered -> https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/producer/HollowProducer.java#L476

The idea would be that developers could implement their own `BlobStorageCleaner` and decide how they want to remove their snapshots, deltas and reverse deltas. Perhaps you want to clean snapshots but you don;t want to clean deltas. Up to them

**Comment by mafa73** [comment]
I would like to have that feature. Currently we have implemented this functionality in the application that produces the snapshots/deltas by keeping x number of files.

**Comment by rpalcolea** [comment]
Any thoughts on this @dkoszewnik @toolbear ?

**Comment by rpalcolea** [comment]
Implemented this in https://github.com/Netflix/hollow/pull/94
