### ISSUE TITLE
Consumer data TTL?

### ISSUE THREAD

**Issue by shakedzy** [Netflix/hollow#96]
Hi,
I was wondering if there's a way to add TTL (time-to-live) for the data cached by the consumer? Meaning, let's say the data should be updated every 24h by the producer. If the producer failed, I'd rather the consumers will drop the data, let say after 30h. Is there a way to do that? Can this be easily added?

**Comment by rpalcolea** [comment]
@shakedzy I'd suggest posting this in the gitter room -> https://gitter.im/Netflix/hollow?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by lkancode** [comment]
Hi Shakedzy,
There is no TTL concept for data loaded on consumer but I would like to understand your use case a little better. Please post more details in gitter room. Thank you. 
Lavanya
